### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by martijndierckx** [ptr727/NxWitness#59]
I've been playing around to see whether the licensing issue really is an issue.

What I've tried:
1. Played with both your docker image and thehomerepot one.
2. Tried deleting the container, and recreating it from the docker-compose (via portainer)
3. Tried starting with version 4.2 in the docker-image config of the docker-compose file. And then updating it to 'latest'. (via portainer)

To test if the license would break, I would activate a trial license and note down the HWID.
And then verify if the HWID changed or the trial license got deactivated.
Which never happened ... everything kept working perfect.

So what WILL make the nxwitness in docker setup make things go bad?
I don't want to have any issues with licences.

Please note, I do setup a fixed mac-address in docker-compose:

```
version: "3"

services:
  nx-witness:
    container_name: nx-witness
    image: 'thehomerepot/nxwitness:latest'
    restart: unless-stopped
    environment:
      TZ: "Europe/Brussels"
    volumes:
      - /opt/networkoptix/config:/config
      - /opt/networkoptix/recordings:/archive
    mac_address: "AA:BB:CC:DD:EE:FF" # something real ...
    ports:
      - "7001:7001"
```
